### ISSUE TITLE
Suggestion: Keep Rocket --watch running even after an error.

### ISSUE THREAD

**Issue by fi-marco-barbosa** [carlcalderon/Rocket#6]
It would be nice to keep the output in the screen as you keep making changes, regardless of error or not.

See "sass --watch" mode for reference.

That way I can keep updating the file on the fly until the error is gone instead of running the CLI again.

**Comment by carlcalderon** [comment]
Pending on the error importance, syntax errors from the compilers should not break the watch mode. Next update will have less aggressive error handling.

**Comment by carlcalderon** [comment]
Fixed in version 0.2.0.
